import './styles/index.scss'
import './style-media.css'
import './pairs/burger/style.css'
import './pairs/large-title/style.css'
import './pairs/mid-title/style.css'
import './pairs/small-title/style.css'
import './pairs/search-container/style.css'
import './pairs/circle-image/style.css'
import './pairs/video-card/style.css'
import './pairs/arrows/style.css'
import './styles/_header.scss'
import './styles/header-media.css'
import './styles/_left-menu.scss'
import './styles/left-menu-media.css'
import './styles/_video-content.scss'
import './styles/video-content-media.css'
import './styles/_bottom-menu.scss'
import './styles/bottom-menu-media.css'


