import './styles/index.scss'

import './pairs/burger/style.css'
import './pairs/large-title/style.css'
import './pairs/mid-title/style.css'
import './pairs/small-title/style.css'
import './pairs/search-container/style.css'
import './pairs/circle-image/style.css'
import './pairs/video-card/style.css'
import './pairs/arrows/style.css'
import './pairs/video-card-with-left-side-desc/style.css'
import './pairs/subscribe-btn-red/style.css'
import './pages/channel/style.css'
import './pages/video-player/style.css'
import './pairs/like-dis-shared-btn-grey/style.css'
import './pairs/video-player-part/style.css'
import './pairs/switcher/style.css'

